# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebb032b510f2a5df611b09fe8ef60e2f93fc7f770d06b32d87a10dfc283414d84e065ff60e193b85499821c44b5b87eca286a9e28c6ffc0a909edf13fc6edab2

test:
  secret_key_base: 9687dff38c841aec251ee5e2d6f03ab9b7c19d84df2ae2a221d5642c46a439dd1a087d986bdfc31616cca24b561dd6cdd75e2e3e3fdb6dd44699cc6e3062aa02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
